# Generated by Django 4.1.7 on 2023-03-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('avg_temperature_max', models.DecimalField(decimal_places=2, help_text='in degrees Celsius', max_digits=6, null=True)),
                ('avg_temperature_min', models.DecimalField(decimal_places=2, help_text='in degrees Celsius', max_digits=6, null=True)),
                ('total_precipitation', models.DecimalField(decimal_places=2, help_text='in centimeters', max_digits=7, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.weatherstation')),
            ],
            options={
                'ordering': ('station__code', 'year'),
                'unique_together': {('station', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WeatherDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.SmallIntegerField(help_text='in tenths of a degree Celsius', null=True)),
                ('temperature_min', models.SmallIntegerField(help_text='in tenths of a degree Celsius', null=True)),
                ('precipitation', models.PositiveSmallIntegerField(help_text='in tenths of a millimeter', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.weatherstation')),
            ],
            options={
                'ordering': ('station__code', 'date'),
                'unique_together': {('station', 'date')},
            },
        ),
    ]
