# Generated by Django 4.1.7 on 2023-03-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('avg_temperature_max', models.SmallIntegerField(help_text='in degrees Celsius', null=True)),
                ('avg_temperature_min', models.SmallIntegerField(help_text='in degrees Celsius', null=True)),
                ('total_precipitation', models.PositiveSmallIntegerField(help_text='in centimeters', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.weatherstation', unique_for_year='year')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.SmallIntegerField(help_text='in tenths of a degree Celsius', null=True)),
                ('temperature_min', models.SmallIntegerField(help_text='in tenths of a degree Celsius', null=True)),
                ('precipitation', models.PositiveSmallIntegerField(help_text='in tenths of a millimeter', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.weatherstation', unique_for_date='date')),
            ],
        ),
    ]
