# Generated by Django 4.1.7 on 2023-03-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherday',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.weatherstation'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='weatherstats',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.weatherstation'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherday',
            unique_together={('station', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='weatherstats',
            unique_together={('station', 'year')},
        ),
    ]
